name = "charity-tracker-qwik"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "charity-tracker-qwik-db"
database_id = "4b7b5031-1844-4ed9-aac0-fcb0e4bf0b3d"