name = "charity-tracker-qwik"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

[env.production]

[env.production.vars]
ENVIRONMENT = "production"
JWT_SECRET = "your-jwt-secret-here"
STRIPE_SECRET_KEY = "your-stripe-secret"
STRIPE_WEBHOOK_SECRET = "your-stripe-webhook-secret"

[[env.production.d1_databases]]
binding = "DB"
database_name = "charity-tracker-qwik-db"
database_id = "4b7b5031-1844-4ed9-aac0-fcb0e4bf0b3d"

[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "your-kv-namespace-id"

[[env.production.r2_buckets]]
binding = "RECEIPTS"
bucket_name = "charity-receipts"

[env.preview]

[env.preview.vars]
ENVIRONMENT = "preview"
JWT_SECRET = "your-jwt-secret-here"
STRIPE_SECRET_KEY = "your-stripe-secret"
STRIPE_WEBHOOK_SECRET = "your-stripe-webhook-secret"

[[env.preview.kv_namespaces]]
binding = "SESSIONS"
id = "your-preview-kv-id"

[[env.preview.r2_buckets]]
binding = "RECEIPTS"
bucket_name = "charity-receipts-preview"