name = "charity-tracker-qwik"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "charity-tracker-db"
database_id = "your-database-id-here"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }

# KV namespace for sessions
[[kv_namespaces]]
binding = "SESSIONS"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-id"

# R2 bucket for file storage (receipts)
[[r2_buckets]]
binding = "RECEIPTS"
bucket_name = "charity-receipts"

# Environment variables (will be set in Cloudflare dashboard)
[vars]
JWT_SECRET = "your-jwt-secret-here"
STRIPE_SECRET_KEY = "your-stripe-secret"
STRIPE_WEBHOOK_SECRET = "your-stripe-webhook-secret"